//! The `crypto` module provides the cryptographic primitives for QRASL.

use pqcrypto_traits::sign::{DetachedSignature, PublicKey, SecretKey};
use pqcrypto_dilithium::dilithium5;
use blake3::hash as blake3_hash;

// Correctly get the lengths by calling the library's functions.
// Note: These are functions, not constants, so we call them to get the value.
pub const PUBLIC_KEY_LENGTH: usize = dilithium5::public_key_bytes();
pub const SECRET_KEY_LENGTH: usize = dilithium5::secret_key_bytes();
pub const SIGNATURE_LENGTH: usize = dilithium5::signature_bytes();

/// A public key for the Dilithium PQC signature scheme, as a byte array.
pub type PublicKeyBytes = [u8; PUBLIC_KEY_LENGTH];

/// A secret key for the Dilithium PQC signature scheme, as a byte array.
pub type SecretKeyBytes = [u8; SECRET_KEY_LENGTH];

/// A signature generated by the Dilithium PQC signature scheme, as a byte array.
pub type SignatureBytes = [u8; SIGNATURE_LENGTH];

/// Generates a new Dilithium keypair.
pub fn generate_keypair() -> (PublicKeyBytes, SecretKeyBytes) {
    let (pk, sk) = dilithium5::keypair();
    let pk_bytes: [u8; PUBLIC_KEY_LENGTH] = pk.as_bytes().try_into().expect("pk wrong size");
    let sk_bytes: [u8; SECRET_KEY_LENGTH] = sk.as_bytes().try_into().expect("sk wrong size");
    (pk_bytes, sk_bytes)
}

/// Derives the public key from a secret key.
/// In Dilithium, the public key is embedded in the secret key.
pub fn keypair_from_secret_key(sk_bytes: &SecretKeyBytes) -> (PublicKeyBytes, SecretKeyBytes) {
    // The public key is the last PUBLIC_KEY_LENGTH bytes of the secret key.
    let pk_offset = SECRET_KEY_LENGTH - PUBLIC_KEY_LENGTH;
    let pk_bytes: PublicKeyBytes = sk_bytes[pk_offset..].try_into().expect("Unable to extract public key from secret key");
    (pk_bytes, *sk_bytes)
}


/// Signs a message with a secret key using detached signatures.
pub fn sign(msg: &[u8], sk_bytes: &SecretKeyBytes) -> SignatureBytes {
    let sk = dilithium5::SecretKey::from_bytes(sk_bytes).expect("Failed to create secret key from bytes");
    let signature = dilithium5::detached_sign(msg, &sk);
    signature.as_bytes().try_into().expect("signature wrong size")
}

/// Verifies a detached signature on a message with a public key.
pub fn verify(sig_bytes: &SignatureBytes, msg: &[u8], pk_bytes: &PublicKeyBytes) -> bool {
    let pk = dilithium5::PublicKey::from_bytes(pk_bytes).expect("Failed to create public key from bytes");
    let sig = dilithium5::DetachedSignature::from_bytes(sig_bytes).expect("Failed to create signature from bytes");
    dilithium5::verify_detached_signature(&sig, msg, &pk).is_ok()
}

/// Hashes a byte slice using BLAKE3.
pub fn hash(data: &[u8]) -> [u8; 32] {
    blake3_hash(data).into()
}

#[cfg(test)]
mod tests;
