import hashlib
import json
from time import time
from .intent import Solution

class Block:
    """
    A single block in a DAG-based blockchain.
    Its payload consists of 'solutions' generated by a solver from user intents.
    """
    def __init__(self, index, solutions, parent_hashes):
        self.index = index
        self.timestamp = time()
        self.solutions = solutions  # Changed from 'transactions' to 'solutions'
        self.parent_hashes = sorted(list(parent_hashes))
        self.solution = None  # The solution to the PoS problem (mining)
        self.hash = None      # The hash is calculated after the solution is found

    def calculate_hash(self):
        """
        Calculates the SHA-256 hash of the block.
        The hash is dependent on all block data, including the list of solutions.
        """
        # Convert Solution objects to a list of dictionaries to make them JSON serializable
        solutions_as_dicts = [s.to_dict() for s in self.solutions]

        block_dict = {
            'index': self.index,
            'timestamp': self.timestamp,
            'solutions': solutions_as_dicts,
            'parent_hashes': self.parent_hashes,
            'solution': self.solution,
        }
        # Using sort_keys=True ensures that the JSON string is always the same for the same data
        block_string = json.dumps(block_dict, sort_keys=True).encode()
        return hashlib.sha256(block_string).hexdigest()
